### ISSUE TITLE
general interface suggestions

### ISSUE THREAD

**Issue by MarioPeper** [Correct-Syntax/Gimel-Studio#5]
First of all it's nice that there is now a dark theme. But it turns out very modest. I attach a screenshot of Gimel-studio and my Blender theme. You said the window frame was controlled by the OS but on Ubuntu I also use a dark theme.
The Node Properties window takes too much space. Here the lines should scale together when you scale the window.
 The render Image and Quick export make no sense and export can fit into the output node.
But the behaviour of the node editor itself makes the least sense to me. Gimel Studio is the first node editor I know that can only connect one node to another.
This is basically just another way of representing a layer workflow.
Except that you can save a setup and apply it to other files. But if you want to do that you should include a batch processor, so that you can select multiple files ( or folders ) and then run one (or more) previously saved node setups.
![Gimel](https://user-images.githubusercontent.com/66747679/93331930-51e82900-f821-11ea-9ab1-80a0c7d7b6a0.png)
![Blender](https://user-images.githubusercontent.com/66747679/93331937-53195600-f821-11ea-82a2-de6efa56ac27.png)

**Comment by Correct-Syntax** [comment]
I am actually working on improving the interface in major ways for the next version so these suggestions are welcome.

**Dark theme**: Yes, the current "dark theme" is still relying on the OS for certain elements. The changes I plan to make in the next version(s) will fix at least some of the issues.

**Node Properties window**: All the panels in the interface are resizable, including the Node Properties window. Except for the Node Graph panel, the other panels can be rearranged in any order you like too. I am not sure if this is what you are referring to or not.  You can see what I mean by looking at the different layouts in the first image on [this page](https://correctsyntax.com/projects/gimel-studio/)

**behavior of the node editor** I fully understand your confusion with this. The ability to connect one node to more than one other node is a feature I am working on. I agree that this is currently limiting. The work-around (for now), is to add another Image node, etc. but I definitely want to have this ability. Blender's node editor (with a few other editors I've seen) is my mai inspiration for Gimel Studio's node graph.

Thank you for your feedback. :)

**Comment by MarioPeper** [comment]
Yeah that sounds good, gimel-studio is still young.
What I actually meant with the space was the buttons: Render Image, Quick Export, View and Export are not necessary at all and so screen space is freed up. If the line spacing would be reduced when resizing node properties you would have even more space.

**Comment by Correct-Syntax** [comment]
I've actually already implemented these things in the newest commits (before I even saw your last comment!). I agree with the wasted space with those buttons -which is why I moved them to a menu. :)

Thanks!

**Comment by Correct-Syntax** [comment]
@MarioPeper,

**Dark theme**

From your screenshot, it looks like (with the current interface) all that needs to be done is just allow for dark window borders (e.g. where "Node Graph" title is...) then your OS dark theme handles the rest. Other than the icons, I guess....

So, I will try to implement a setting for this so that it looks better for now. Until I get something better (see below):

I am planning to eventually implement custom widgets so that the OS no longer takes over and makes it look ugly like this (including the menus, etc).

The reason I mention this is that it seems that the dark theme problems seem to be the only thing not resolved for this issue.

Thanks again for your feedback. Sorry the dark theme wasn't what you were expecting! :)

**Comment by MarioPeper** [comment]
No problem. But blender also uses a completely own UI and is not interested in the OS ones.

**Comment by Correct-Syntax** [comment]
> No problem. But blender also uses a completely own UI and is not interested in the OS ones.

Yeah. I am hoping to get there with non-OS widgets, just like blender. 

The only reason I haven't fully gone to custom widgets (and thus a truly "dark" theme) is the Properties Panel widgets. The Node Graph and Image Viewport are already fully custom and thus for those it would be just as simple as adding settings to change/customize those colors. I am also already able to do custom menus, etc. as well. I am just cautious about making everything custom except the properties panel widgets (a.k.a: leaving them as native OS widgets) in fear that it might look a bit strange. I have ways I could create the custom widgets for that, but (of course) it's a lot of work. Eventually, I probably will do that.

**Comment by Correct-Syntax** [comment]
Thinking out-loud: Maybe, it should just be done in baby-steps... like starting with the scrollbars and menus...then eventually get around to the property panel widgets.....

**Comment by MarioPeper** [comment]
I do not fully understand the problem. From a design perspective, it is much easier to create the interface without any interference from the OS.

**Comment by Correct-Syntax** [comment]
> I do not fully understand the problem. From a design perspective, it is much easier to create the interface without any interference from the OS.

True. The UI toolkit I use provides native (non-customizable) widgets. That's really the main problem/challenge. :/

> I also don't think that there has to be only one dark theme. You should be able to choose between at least light and dark. A dark scheme is of little use in bright sunlight. Better would be of course a few more. Or as with blender that you can set everything yourself. Then the community would quickly invent many more.

Yes, that would be my intention.

> But you should put the coding power in other things at the beginning.

Yes. Definitely. Hence my though about taking it in "baby-steps". 

UI themes aren't usually a big priority. I'd just like a truly dark theme for the default. (Not that I don't like the current setup. It looks best on the default OS themes, which your not using in your case) 

Plus, with this issue open it would be nice to resolve it. :)

**Comment by Correct-Syntax** [comment]
![Screenshot 2020-11-26 194615](https://user-images.githubusercontent.com/60711001/100405798-fa88e500-3029-11eb-8a2b-f224835b2698.jpg)

I've implemented a dark theme. It still needs work, but I think it's O.K for now -good enough to close this issue. It should be in the next release.

Thanks @MarioPeper for your feedback, as always. :)
