### ISSUE TITLE
Suggestions for the texture workflow

### ISSUE THREAD

**Issue by MarioPeper** [Correct-Syntax/Gimel-Studio#6]
I find the new material flow very good and easy implemented. So keep up the good work :-)
As already mentioned, Gimel-Studio should be able to connect one node with several nodes (otherwise a node system hardly makes sense). I tried 3 other open source texture node systems: Material Maker, TextureLab and Graph.ical.
Material Maker has the most functions, but is already so complex that I can stay with the cycle editor. TextureLab makes a very good impression. But it only uses procedural textures and can't load an image map. This is a pity, because the interface looks quite good. But my absolute favorite is the web application Graph.ical. Not only the selection of the 42 nodes is excellent for 3D graphic artists. Above all, it is the fast and dirty workflow that outshines all others. You press the space bar, then 2-3 letters, the cursor down and then Enter or the mouse button. A new node is appended to the selected one. Double-clicking or Ctrl and clicking enlarges the node. You can select (and edit) one node and Ctrl+click to display another. In the large view you have a tiled preview (seamless) and a button to save. You cannot even specify a file name.
But the whole thing is so fast that you can actually edit images in seconds.
The only disadvantage: no 3D preview. 
By the way, it works with dark reader ;-)
So you should have to look at the three apps.

**Comment by Correct-Syntax** [comment]
I have tried Material Maker and Graph.ical. I think I will take a look at TextureLab too.

I plan to have a similar way of adding nodes to the node graph in Gimel Studio as you explained, with some differences. 

I am going to be honest here, but I actually didn't like everything about the flow of Graph.ical. I personally like more along the lines of Blender's node editor. That's the reason you have user preferences, though -one person likes something different than another, right? :-)

**Comment by MarioPeper** [comment]
LOL  Yes it looks like I am the only one who likes Graph.ical
I only wanted to describe the workflow once, because I realize that 90% don't understand it. I discovered it very early, because I was looking for an open source alternative to Substance Designer for a long time. At that time there was no alternative, otherwise I probably wouldn't have bothered with it. ;-)
But also agree to orientate yourself with Gimel-Studio towards the Blender Editor. 
So I'm really looking forward to Gimel-Studio with more nodes and a better connection behaviour.
Thank you for being open for my ideas and of course for making Gimel-Studio.

**Comment by Correct-Syntax** [comment]
I have just implemented better connection behavior for the nodes. It's in the master branch if you would like to try it. :) I am still working on getting all the nodes re-implemented for the huge changes I made to the api, backend, etc. though.


> Thank you for being open for my ideas and of course for making Gimel-Studio.
HalleluYAH! Glad you like it. Your suggestions and feedback have been a great help.
